// Generated by nchito-shared/generate.mjs from taxonomy.json — do not edit.
// Run `node nchito-shared/generate.mjs` after changing it.

const SERVICE_GROUPS = [
  { id: "trades", label: "Building & Trades", short: "Building", blurb: "The people who build and fix the physical thing.", emoji: "🧱" },
  { id: "home", label: "Home & Care", short: "Home & care", blurb: "Work inside someone's home, and the people in it.", emoji: "🏡" },
  { id: "food", label: "Food & Hospitality", short: "Food & events", blurb: "Cooking, serving and feeding a room.", emoji: "🍲" },
  { id: "logistics", label: "Transport & Errands", short: "Transport", blurb: "Moving things and people across town.", emoji: "🛵" },
  { id: "style", label: "Style & Lifestyle", short: "Hair & style", blurb: "Hair, clothes, skin and looking after yourself.", emoji: "✂️" },
  { id: "creative", label: "Creative & Media", short: "Design/media", blurb: "Design, sound, pictures and the web.", emoji: "🎨" },
  { id: "learning", label: "Learning & Guidance", short: "Teaching", blurb: "Teaching, coaching and counsel.", emoji: "📚" },
  { id: "office", label: "Office & Admin", short: "Office work", blurb: "The paperwork behind a small business.", emoji: "🗂️" },
];

const CATEGORIES = [
  { id: "bricklaying", label: "Bricklaying & Masonry", short: "Bricklaying", emoji: "🧱", group: "trades" },
  { id: "carpentry", label: "Carpentry & Joinery", short: "Carpentry", emoji: "🪚", group: "trades" },
  { id: "painting", label: "Painting & Decorating", short: "Painting", emoji: "🖌️", group: "trades" },
  { id: "welding", label: "Welding & Metalwork", short: "Welding", emoji: "🔥", group: "trades" },
  { id: "plumbing", label: "Plumbing", short: "Plumbing", emoji: "🚰", group: "trades" },
  { id: "electrical", label: "Electrical Services", short: "Electrical", emoji: "⚡", group: "trades" },
  { id: "repairs", label: "Repairs & Technical", short: "Repairs", emoji: "🔧", group: "trades" },
  { id: "home_services", label: "Home Services", short: "Home help", emoji: "🏠", group: "home" },
  { id: "cleaning", label: "Cleaning", short: "Cleaning", emoji: "🧹", group: "home" },
  { id: "laundry", label: "Washing & Ironing", short: "Washing", emoji: "👕", group: "home" },
  { id: "security", label: "Security & Guarding", short: "Security", emoji: "🛡️", group: "home" },
  { id: "childcare", label: "Childcare & Nannies", short: "Childcare", emoji: "👶", group: "home" },
  { id: "farm", label: "Farm & Garden", short: "Farm/garden", emoji: "🌱", group: "home" },
  { id: "catering", label: "Catering", short: "Catering", emoji: "🍽️", group: "food" },
  { id: "chef", label: "Chefs & Cooks", short: "Chef/cook", emoji: "👨‍🍳", group: "food" },
  { id: "restaurant", label: "Restaurant & Bar Work", short: "Restaurant", emoji: "🍽️", group: "food" },
  { id: "events", label: "Events & Functions", short: "Events", emoji: "🎉", group: "food" },
  { id: "delivery", label: "Delivery & Errands", short: "Delivery", emoji: "🛵", group: "logistics" },
  { id: "messenger", label: "Messengers", short: "Messenger", emoji: "✉️", group: "logistics" },
  { id: "loading", label: "Loading & Moving", short: "Loading", emoji: "📦", group: "logistics" },
  { id: "driving", label: "Driving", short: "Driving", emoji: "🚗", group: "logistics" },
  { id: "beauty", label: "Beauty & Grooming", short: "Beauty", emoji: "💅", group: "style" },
  { id: "barbering", label: "Barbershops", short: "Barbering", emoji: "💈", group: "style" },
  { id: "salon", label: "Salon & Hair", short: "Salon", emoji: "💇‍♀️", group: "style" },
  { id: "cosmetics", label: "Cosmetics & Make-up", short: "Cosmetics", emoji: "💄", group: "style" },
  { id: "tailoring", label: "Sewing & Tailoring", short: "Sewing", emoji: "🧵", group: "style" },
  { id: "lifestyle", label: "Lifestyle & Wellness", short: "Lifestyle", emoji: "🧘", group: "style" },
  { id: "digital", label: "Digital & Design", short: "Design", emoji: "💻", group: "creative" },
  { id: "web_design", label: "Web Design & Dev", short: "Web design", emoji: "🌐", group: "creative" },
  { id: "music", label: "Music & Sound", short: "Music", emoji: "🎵", group: "creative" },
  { id: "photography", label: "Photo & Video", short: "Photo/video", emoji: "📷", group: "creative" },
  { id: "tutoring", label: "Tutoring & Lessons", short: "Tutoring", emoji: "📖", group: "learning" },
  { id: "teaching", label: "Teaching Services", short: "Teaching", emoji: "🎓", group: "learning" },
  { id: "coaching", label: "Coaching & Training", short: "Coaching", emoji: "🏃", group: "learning" },
  { id: "counselling", label: "Counselling", short: "Counselling", emoji: "🫂", group: "learning" },
  { id: "ministry", label: "Preaching & Ministry", short: "Ministry", emoji: "🙏", group: "learning" },
  { id: "office_admin", label: "Office & Admin Support", short: "Office admin", emoji: "🗂️", group: "office" },
  { id: "bookkeeping", label: "Bookkeeping & Accounts", short: "Bookkeeping", emoji: "📒", group: "office" },
  { id: "translation", label: "Translation & Typing", short: "Translation", emoji: "🗣️", group: "office" },
];

const CATEGORY_BY_ID = Object.fromEntries(CATEGORIES.map(c => [c.id, c]));
const GROUP_BY_ID = Object.fromEntries(SERVICE_GROUPS.map(g => [g.id, g]));
const categoriesIn = groupId => CATEGORIES.filter(c => c.group === groupId);

/* A category code from an older build, or a typo, must not blank out a card. */
const categoryLabel = id => (CATEGORY_BY_ID[id] || { label: 'Other' }).label;
const categoryEmoji = id => (CATEGORY_BY_ID[id] || { emoji: '\u{1F4CC}' }).emoji;
