// Generated by nchito-shared/generate.mjs from languages.json — do not edit.
// Run `node nchito-shared/generate.mjs` after changing it.

/* 5 languages · 3 offered in the picker.
   A language below 45% coverage is listed as coming soon rather than
   shipped half-English, and every untranslated string falls back to English. */
const LANGUAGES = [
  { code: "en", name: "English", native: "English", reviewed: true, available: true, coverage: 1.000, asr: "en-ZA", tts: "en-ZA", note: "The fallback for every other language." },
  { code: "ny", name: "Nyanja", native: "Chinyanja", reviewed: false, available: true, coverage: 1.000, asr: null, tts: null, note: "Lusaka's lingua franca. No browser or phone OS ships speech recognition or a voice for it." },
  { code: "bem", name: "Bemba", native: "Ichibemba", reviewed: false, available: true, coverage: 1.000, asr: null, tts: null, note: "The Copperbelt and much of the north. No speech support anywhere off the shelf." },
  { code: "toi", name: "Tonga", native: "Chitonga", reviewed: false, available: false, coverage: 0.339, asr: null, tts: null, note: "Southern Province. Core navigation only so far." },
  { code: "loz", name: "Lozi", native: "Silozi", reviewed: false, available: false, coverage: 0.339, asr: null, tts: null, note: "Western Province. Core navigation only so far." },
];

const STRINGS = {
  "en": {"app.tagline":"Find work. Get paid.","nav.findWork":"Find work","nav.tasks":"Tasks","nav.numbers":"Numbers","nav.chats":"Chats","nav.wallet":"Wallet","nav.office":"Office","nav.profile":"Profile","nav.hire":"Hire","nav.myJobs":"My jobs","nav.circle":"Chilimba","title.workNearYou":"Work near you","title.wallet":"Wallet","title.myNumbers":"My numbers","title.quickTasks":"Quick Tasks","title.hireSomeone":"Hire someone","title.jobsIPosted":"Jobs I posted","title.chilimba":"My Chilimba","money.balance":"Available balance","money.cashOut":"Cash out","money.getPaidEarly":"Get paid early","money.inEscrow":"Held safely","money.youReceive":"You receive","money.fee":"Our fee","money.cashNearMe":"Find cash near me","action.apply":"Apply","action.applied":"Application sent","action.message":"Message","action.send":"Send","action.back":"Back","action.search":"Search","action.postJob":"Post job","action.record":"Record a voice note","action.stop":"Stop","action.play":"Play","action.readAloud":"Read this aloud","word.yes":"Yes","word.no":"No","word.thanks":"Thank you","word.welcome":"Welcome","word.today":"Today","word.language":"Language","word.name":"Name","word.town":"Town","word.near":"Near you","word.urgent":"Urgent","circle.title":"Chilimba","circle.yourTurn":"Your turn","circle.members":"Members","circle.round":"Round","circle.contribute":"Contribute","circle.paidIn":"Paid in","circle.received":"Received","circle.waiting":"Still to contribute","voice.notReviewed":"This translation has not yet been checked by a native speaker. Anything that looks wrong probably is — please tell us.","voice.noSpeech":"Your phone cannot listen in this language yet, so type or send a voice note instead."},
  "ny": {"app.tagline":"Pezani ntchito. Landirani ndalama.","nav.findWork":"Pezani ntchito","nav.tasks":"Ntchito zazing'ono","nav.numbers":"Manambala","nav.chats":"Mauthenga","nav.wallet":"Chikwama","nav.office":"Ofesi","nav.profile":"Za ine","nav.hire":"Lembani munthu","nav.myJobs":"Ntchito zanga","nav.circle":"Chilimba","title.workNearYou":"Ntchito pafupi nanu","title.wallet":"Chikwama changa","title.myNumbers":"Manambala anga","title.quickTasks":"Ntchito zofulumira","title.hireSomeone":"Lembani wogwira ntchito","title.jobsIPosted":"Ntchito zomwe ndalemba","title.chilimba":"Chilimba changa","money.balance":"Ndalama zomwe muli nazo","money.cashOut":"Tulutsani ndalama","money.getPaidEarly":"Landirani ndalama msanga","money.inEscrow":"Zasungidwa bwino","money.youReceive":"Mudzalandira","money.fee":"Malipiro athu","money.cashNearMe":"Pezani ndalama pafupi","action.apply":"Funsani ntchito","action.applied":"Pempho latumizidwa","action.message":"Tumizani uthenga","action.send":"Tumizani","action.back":"Bwererani","action.search":"Sakani","action.postJob":"Lembani ntchito","action.record":"Nenani ndi mawu anu","action.stop":"Imani","action.play":"Mvetserani","action.readAloud":"Werengani mokweza","word.yes":"Inde","word.no":"Ayi","word.thanks":"Zikomo","word.welcome":"Takulandirani","word.today":"Lero","word.language":"Chinenero","word.name":"Dzina","word.town":"Tauni","word.near":"Pafupi nanu","word.urgent":"Mwachangu","circle.title":"Chilimba","circle.yourTurn":"Nthawi yanu","circle.members":"Mamembala","circle.round":"Kuzungulira","circle.contribute":"Perekani","circle.paidIn":"Zomwe mwapereka","circle.received":"Zomwe mwalandira","circle.waiting":"Sanaperekebe","voice.notReviewed":"Kumasulira uku sikunawunikidwe ndi mwiniwake wa chinenerochi. Ngati chinachake sichili bwino, tidziwitseni.","voice.noSpeech":"Foni yanu sikhoza kumvetsera chinenero ichi. Lembani kapena tumizani mawu anu."},
  "bem": {"app.tagline":"Fwayeni incito. Poleni indalama.","nav.findWork":"Fwayeni incito","nav.tasks":"Incito inono","nav.numbers":"Inambala","nav.chats":"Amashiwi","nav.wallet":"Icikwama","nav.office":"Ofeshi","nav.profile":"Pali ine","nav.hire":"Lembeni umuntu","nav.myJobs":"Incito shandi","nav.circle":"Icilimba","title.workNearYou":"Incito mupepi nenu","title.wallet":"Icikwama candi","title.myNumbers":"Inambala shandi","title.quickTasks":"Incito sha bwangu","title.hireSomeone":"Lembeni uwabomba","title.jobsIPosted":"Incito nalemba","title.chilimba":"Icilimba candi","money.balance":"Indalama mwakwata","money.cashOut":"Fumyeni indalama","money.getPaidEarly":"Poleni indalama bwangu","money.inEscrow":"Shasungwa bwino","money.youReceive":"Mukapokelela","money.fee":"Indalama shesu","money.cashNearMe":"Fwayeni indalama mupepi","action.apply":"Lombeni incito","action.applied":"Icilomba nacitumwa","action.message":"Tumeni ishiwi","action.send":"Tumeni","action.back":"Bwelelenimo","action.search":"Fwayeni","action.postJob":"Lembeni incito","action.record":"Landeni no kwasa kwenu","action.stop":"Imeni","action.play":"Umfweni","action.readAloud":"Belengeni mu kwasa","word.yes":"Ee","word.no":"Awe","word.thanks":"Natotela","word.welcome":"Mwaiseni","word.today":"Lelo","word.language":"Ululimi","word.name":"Ishina","word.town":"Itauni","word.near":"Mupepi nenu","word.urgent":"Bwangu bwangu","circle.title":"Icilimba","circle.yourTurn":"Inshita yenu","circle.members":"Abamembala","circle.round":"Ukushinguluka","circle.contribute":"Peeleni","circle.paidIn":"Ifyo mwapeela","circle.received":"Ifyo mwapokelela","circle.waiting":"Tabalapeela","voice.notReviewed":"Uku ukupilibula tabalakubebeta kuli abene ba lulimi. Nga cimo tacili bwino, tubebeni.","voice.noSpeech":"Ifoni yenu tailomfwa ulu lulimi. Lembeni nangula tumeni akwasa kenu."},
  "toi": {"app.tagline":"Jana mulimo. Tambula mali.","nav.findWork":"Jana mulimo","nav.tasks":"Tasks","nav.numbers":"Numbers","nav.chats":"Chats","nav.wallet":"Wallet","nav.office":"Office","nav.profile":"Profile","nav.hire":"Hire","nav.myJobs":"My jobs","nav.circle":"Chilimba","title.workNearYou":"Mulimo afwiifwi","title.wallet":"Wallet","title.myNumbers":"My numbers","title.quickTasks":"Quick Tasks","title.hireSomeone":"Hire someone","title.jobsIPosted":"Jobs I posted","title.chilimba":"My Chilimba","money.balance":"Mali ngomujisi","money.cashOut":"Gwisya mali","money.getPaidEarly":"Get paid early","money.inEscrow":"Held safely","money.youReceive":"You receive","money.fee":"Our fee","money.cashNearMe":"Find cash near me","action.apply":"Kumbila mulimo","action.applied":"Application sent","action.message":"Message","action.send":"Tuma","action.back":"Joka","action.search":"Yandaula","action.postJob":"Post job","action.record":"Record a voice note","action.stop":"Stop","action.play":"Play","action.readAloud":"Read this aloud","word.yes":"Inzya","word.no":"Pe","word.thanks":"Twalumba","word.welcome":"Mwabonwa","word.today":"Sunu","word.language":"Mwaambo","word.name":"Zina","word.town":"Town","word.near":"Afwiifwi","word.urgent":"Urgent","circle.title":"Chilimba","circle.yourTurn":"Your turn","circle.members":"Members","circle.round":"Round","circle.contribute":"Contribute","circle.paidIn":"Paid in","circle.received":"Received","circle.waiting":"Still to contribute","voice.notReviewed":"This translation has not yet been checked by a native speaker. Anything that looks wrong probably is — please tell us.","voice.noSpeech":"Your phone cannot listen in this language yet, so type or send a voice note instead."},
  "loz": {"app.tagline":"Fumana musebezi. Amuhela mali.","nav.findWork":"Fumana musebezi","nav.tasks":"Tasks","nav.numbers":"Numbers","nav.chats":"Chats","nav.wallet":"Wallet","nav.office":"Office","nav.profile":"Profile","nav.hire":"Hire","nav.myJobs":"My jobs","nav.circle":"Chilimba","title.workNearYou":"Musebezi bukaufi","title.wallet":"Wallet","title.myNumbers":"My numbers","title.quickTasks":"Quick Tasks","title.hireSomeone":"Hire someone","title.jobsIPosted":"Jobs I posted","title.chilimba":"My Chilimba","money.balance":"Mali eo munani ona","money.cashOut":"Zwisa mali","money.getPaidEarly":"Get paid early","money.inEscrow":"Held safely","money.youReceive":"You receive","money.fee":"Our fee","money.cashNearMe":"Find cash near me","action.apply":"Kupa musebezi","action.applied":"Application sent","action.message":"Message","action.send":"Luma","action.back":"Kuta","action.search":"Bata","action.postJob":"Post job","action.record":"Record a voice note","action.stop":"Stop","action.play":"Play","action.readAloud":"Read this aloud","word.yes":"Eni","word.no":"Awa","word.thanks":"Nitumezi","word.welcome":"Mu amuhelwe","word.today":"Kacenu","word.language":"Puo","word.name":"Libizo","word.town":"Town","word.near":"Bukaufi","word.urgent":"Urgent","circle.title":"Chilimba","circle.yourTurn":"Your turn","circle.members":"Members","circle.round":"Round","circle.contribute":"Contribute","circle.paidIn":"Paid in","circle.received":"Received","circle.waiting":"Still to contribute","voice.notReviewed":"This translation has not yet been checked by a native speaker. Anything that looks wrong probably is — please tell us.","voice.noSpeech":"Your phone cannot listen in this language yet, so type or send a voice note instead."},
};

/* Which keys are genuinely translated, as opposed to falling back. The UI uses
   this to be honest about a partly translated screen instead of pretending. */
const TRANSLATED = {
  "en": ["app.tagline","nav.findWork","nav.tasks","nav.numbers","nav.chats","nav.wallet","nav.office","nav.profile","nav.hire","nav.myJobs","nav.circle","title.workNearYou","title.wallet","title.myNumbers","title.quickTasks","title.hireSomeone","title.jobsIPosted","title.chilimba","money.balance","money.cashOut","money.getPaidEarly","money.inEscrow","money.youReceive","money.fee","money.cashNearMe","action.apply","action.applied","action.message","action.send","action.back","action.search","action.postJob","action.record","action.stop","action.play","action.readAloud","word.yes","word.no","word.thanks","word.welcome","word.today","word.language","word.name","word.town","word.near","word.urgent","circle.title","circle.yourTurn","circle.members","circle.round","circle.contribute","circle.paidIn","circle.received","circle.waiting","voice.notReviewed","voice.noSpeech"],
  "ny": ["app.tagline","nav.findWork","nav.tasks","nav.numbers","nav.chats","nav.wallet","nav.office","nav.profile","nav.hire","nav.myJobs","nav.circle","title.workNearYou","title.wallet","title.myNumbers","title.quickTasks","title.hireSomeone","title.jobsIPosted","title.chilimba","money.balance","money.cashOut","money.getPaidEarly","money.inEscrow","money.youReceive","money.fee","money.cashNearMe","action.apply","action.applied","action.message","action.send","action.back","action.search","action.postJob","action.record","action.stop","action.play","action.readAloud","word.yes","word.no","word.thanks","word.welcome","word.today","word.language","word.name","word.town","word.near","word.urgent","circle.title","circle.yourTurn","circle.members","circle.round","circle.contribute","circle.paidIn","circle.received","circle.waiting","voice.notReviewed","voice.noSpeech"],
  "bem": ["app.tagline","nav.findWork","nav.tasks","nav.numbers","nav.chats","nav.wallet","nav.office","nav.profile","nav.hire","nav.myJobs","nav.circle","title.workNearYou","title.wallet","title.myNumbers","title.quickTasks","title.hireSomeone","title.jobsIPosted","title.chilimba","money.balance","money.cashOut","money.getPaidEarly","money.inEscrow","money.youReceive","money.fee","money.cashNearMe","action.apply","action.applied","action.message","action.send","action.back","action.search","action.postJob","action.record","action.stop","action.play","action.readAloud","word.yes","word.no","word.thanks","word.welcome","word.today","word.language","word.name","word.town","word.near","word.urgent","circle.title","circle.yourTurn","circle.members","circle.round","circle.contribute","circle.paidIn","circle.received","circle.waiting","voice.notReviewed","voice.noSpeech"],
  "toi": ["app.tagline","nav.findWork","nav.circle","title.workNearYou","money.balance","money.cashOut","action.apply","action.send","action.back","action.search","word.yes","word.no","word.thanks","word.welcome","word.today","word.language","word.name","word.near","circle.title"],
  "loz": ["app.tagline","nav.findWork","nav.circle","title.workNearYou","money.balance","money.cashOut","action.apply","action.send","action.back","action.search","word.yes","word.no","word.thanks","word.welcome","word.today","word.language","word.name","word.near","circle.title"],
};

const CATEGORY_NAMES = {
  "en": {},
  "ny": {"bricklaying":"Kumanga ndi njerwa","carpentry":"Ukalipentala","painting":"Kupenta","cleaning":"Kuyeretsa","laundry":"Kuchapa ndi kusita","childcare":"Kusunga ana","security":"Kulondera","farm":"Ulimi ndi munda","chef":"Kuphika","catering":"Kuphikira anthu","delivery":"Kutumiza katundu","loading":"Kusenza katundu","driving":"Kuyendetsa galimoto","tailoring":"Kusoka zovala","salon":"Kuluka tsitsi","barbering":"Kumeta","tutoring":"Kuphunzitsa","teaching":"Uphunzitsi","ministry":"Kulalikira","counselling":"Kulangiza","music":"Nyimbo","photography":"Kujambula","messenger":"Kunyamula mauthenga","home_services":"Ntchito zapakhomo"},
  "bem": {"bricklaying":"Ukukuula","carpentry":"Ubukalipentala","painting":"Ukupenta","cleaning":"Ukusangulula","laundry":"Ukucapa","childcare":"Ukusunga abana","security":"Ukulinda","farm":"Ubulimi","chef":"Ukwipika","catering":"Ukwipikila abantu","delivery":"Ukutwala ifintu","loading":"Ukusenda ifintu","driving":"Ukwendesha imotoka","tailoring":"Ukushona ifyakufwala","salon":"Ukuluka umushishi","barbering":"Ukubeya","tutoring":"Ukusambilisha","teaching":"Ubukafundisha","ministry":"Ukushimikila","counselling":"Ukufunda","music":"Inyimbo","photography":"Ukukopa","messenger":"Ukutwala amashiwi","home_services":"Incito sha pang'anda"},
  "toi": {"farm":"Bulimi"},
  "loz": {"farm":"Bulimi"},
};

const LEXICON = {
  "gigs": [
    "ntchito",
    "incito",
    "ncito",
    "nchito",
    "mulimo",
    "musebezi",
    "gig",
    "job",
    "work",
    "basa"
  ],
  "wallet": [
    "ndalama",
    "indalama",
    "chikwama",
    "icikwama",
    "wallet",
    "balance",
    "cash",
    "money",
    "kobili",
    "mali"
  ],
  "tasks": [
    "survey",
    "quick task",
    "tasks"
  ],
  "record": [
    "mbiri",
    "umbiri",
    "record",
    "history"
  ],
  "advance": [
    "msanga",
    "bwangu",
    "early",
    "advance"
  ],
  "agents": [
    "ejenti",
    "agent",
    "float"
  ],
  "circle": [
    "chilimba",
    "icilimba",
    "cilimba",
    "circle",
    "kusunga",
    "ukusunga",
    "saving"
  ],
  "greet": [
    "muli bwanji",
    "muli shani",
    "mwabuka",
    "mwashibukeni",
    "mwapoleni",
    "hello",
    "hey",
    "start",
    "menu"
  ],
  "help": [
    "thandizo",
    "thandiza",
    "ubwafwilisho",
    "help"
  ]
};

const LANG_BY_CODE = Object.fromEntries(LANGUAGES.map(l => [l.code, l]));
