// Generated by nchito-shared/generate.mjs from taxonomy.json — do not edit.
// Run `node nchito-shared/generate.mjs` after changing it.

package com.owenphiri.nchito.data

/**
 * The eight families a service belongs to. Groups exist because 39 flat
 * categories is a wall of chips on a phone and six screens on USSD; nobody
 * browses that. Every surface shows groups first.
 */
enum class ServiceGroup(
    val code: String,
    val label: String,
    /** The label used where a whole menu has to fit one USSD screen. */
    val short: String,
    val blurb: String,
    val emoji: String,
) {
    TRADES(     "trades", "Building & Trades", "Building", "The people who build and fix the physical thing.", "🧱"),
    HOME(       "home", "Home & Care", "Home & care", "Work inside someone's home, and the people in it.", "🏡"),
    FOOD(       "food", "Food & Hospitality", "Food & events", "Cooking, serving and feeding a room.", "🍲"),
    LOGISTICS(  "logistics", "Transport & Errands", "Transport", "Moving things and people across town.", "🛵"),
    STYLE(      "style", "Style & Lifestyle", "Hair & style", "Hair, clothes, skin and looking after yourself.", "✂️"),
    CREATIVE(   "creative", "Creative & Media", "Design/media", "Design, sound, pictures and the web.", "🎨"),
    LEARNING(   "learning", "Learning & Guidance", "Teaching", "Teaching, coaching and counsel.", "📚"),
    OFFICE(     "office", "Office & Admin", "Office work", "The paperwork behind a small business.", "🗂️"),
    ;

    val categories: List<GigCategory> get() = GigCategory.entries.filter { it.group == this }

    companion object {
        fun fromCode(code: String): ServiceGroup? = entries.firstOrNull { it.code == code }
    }
}

/**
 * A service someone can be hired for.
 *
 * [label] is display text and may be reworded freely. [wire] is the value
 * Postgres stores and must never change once shipped: gig rows written months
 * ago still carry it.
 */
enum class GigCategory(
    val wire: String,
    val label: String,
    val short: String,
    val emoji: String,
    val group: ServiceGroup,
) {
    BRICKLAYING  ("bricklaying", "Bricklaying & Masonry", "Bricklaying", "🧱", ServiceGroup.TRADES),
    CARPENTRY    ("carpentry", "Carpentry & Joinery", "Carpentry", "🪚", ServiceGroup.TRADES),
    PAINTING     ("painting", "Painting & Decorating", "Painting", "🖌️", ServiceGroup.TRADES),
    WELDING      ("welding", "Welding & Metalwork", "Welding", "🔥", ServiceGroup.TRADES),
    PLUMBING     ("plumbing", "Plumbing", "Plumbing", "🚰", ServiceGroup.TRADES),
    ELECTRICAL   ("electrical", "Electrical Services", "Electrical", "⚡", ServiceGroup.TRADES),
    REPAIRS      ("repairs", "Repairs & Technical", "Repairs", "🔧", ServiceGroup.TRADES),
    HOME_SERVICES("home_services", "Home Services", "Home help", "🏠", ServiceGroup.HOME),
    CLEANING     ("cleaning", "Cleaning", "Cleaning", "🧹", ServiceGroup.HOME),
    LAUNDRY      ("laundry", "Washing & Ironing", "Washing", "👕", ServiceGroup.HOME),
    SECURITY     ("security", "Security & Guarding", "Security", "🛡️", ServiceGroup.HOME),
    CHILDCARE    ("childcare", "Childcare & Nannies", "Childcare", "👶", ServiceGroup.HOME),
    FARM         ("farm", "Farm & Garden", "Farm/garden", "🌱", ServiceGroup.HOME),
    CATERING     ("catering", "Catering", "Catering", "🍽️", ServiceGroup.FOOD),
    CHEF         ("chef", "Chefs & Cooks", "Chef/cook", "👨‍🍳", ServiceGroup.FOOD),
    RESTAURANT   ("restaurant", "Restaurant & Bar Work", "Restaurant", "🍽️", ServiceGroup.FOOD),
    EVENTS       ("events", "Events & Functions", "Events", "🎉", ServiceGroup.FOOD),
    DELIVERY     ("delivery", "Delivery & Errands", "Delivery", "🛵", ServiceGroup.LOGISTICS),
    MESSENGER    ("messenger", "Messengers", "Messenger", "✉️", ServiceGroup.LOGISTICS),
    LOADING      ("loading", "Loading & Moving", "Loading", "📦", ServiceGroup.LOGISTICS),
    DRIVING      ("driving", "Driving", "Driving", "🚗", ServiceGroup.LOGISTICS),
    BEAUTY       ("beauty", "Beauty & Grooming", "Beauty", "💅", ServiceGroup.STYLE),
    BARBERING    ("barbering", "Barbershops", "Barbering", "💈", ServiceGroup.STYLE),
    SALON        ("salon", "Salon & Hair", "Salon", "💇‍♀️", ServiceGroup.STYLE),
    COSMETICS    ("cosmetics", "Cosmetics & Make-up", "Cosmetics", "💄", ServiceGroup.STYLE),
    TAILORING    ("tailoring", "Sewing & Tailoring", "Sewing", "🧵", ServiceGroup.STYLE),
    LIFESTYLE    ("lifestyle", "Lifestyle & Wellness", "Lifestyle", "🧘", ServiceGroup.STYLE),
    DIGITAL      ("digital", "Digital & Design", "Design", "💻", ServiceGroup.CREATIVE),
    WEB_DESIGN   ("web_design", "Web Design & Dev", "Web design", "🌐", ServiceGroup.CREATIVE),
    MUSIC        ("music", "Music & Sound", "Music", "🎵", ServiceGroup.CREATIVE),
    PHOTOGRAPHY  ("photography", "Photo & Video", "Photo/video", "📷", ServiceGroup.CREATIVE),
    TUTORING     ("tutoring", "Tutoring & Lessons", "Tutoring", "📖", ServiceGroup.LEARNING),
    TEACHING     ("teaching", "Teaching Services", "Teaching", "🎓", ServiceGroup.LEARNING),
    COACHING     ("coaching", "Coaching & Training", "Coaching", "🏃", ServiceGroup.LEARNING),
    COUNSELLING  ("counselling", "Counselling", "Counselling", "🫂", ServiceGroup.LEARNING),
    MINISTRY     ("ministry", "Preaching & Ministry", "Ministry", "🙏", ServiceGroup.LEARNING),
    OFFICE_ADMIN ("office_admin", "Office & Admin Support", "Office admin", "🗂️", ServiceGroup.OFFICE),
    BOOKKEEPING  ("bookkeeping", "Bookkeeping & Accounts", "Bookkeeping", "📒", ServiceGroup.OFFICE),
    TRANSLATION  ("translation", "Translation & Typing", "Translation", "🗣️", ServiceGroup.OFFICE),
    ;

    companion object {
        fun fromWire(wire: String): GigCategory? = entries.firstOrNull { it.wire == wire }
    }
}
