// Generated by nchito-shared/generate.mjs from languages.json — do not edit.
// Run `node nchito-shared/generate.mjs` after changing it.

import Foundation

/// The languages Nchito speaks. `available` is false below 45% coverage:
/// a half-translated interface reads as broken, and broken is worse than English.
enum AppLanguage: String, CaseIterable, Identifiable, Codable {
    case english  = "en"
    case nyanja   = "ny"
    case bemba    = "bem"
    case tonga    = "toi"
    case lozi     = "loz"

    var id: String { rawValue }

    var name: String {
        switch self {
        case .english:  return "English"
        case .nyanja:   return "Nyanja"
        case .bemba:    return "Bemba"
        case .tonga:    return "Tonga"
        case .lozi:     return "Lozi"
        }
    }

    /// The language's name in itself — the only version a speaker of it scans for.
    var nativeName: String {
        switch self {
        case .english:  return "English"
        case .nyanja:   return "Chinyanja"
        case .bemba:    return "Ichibemba"
        case .tonga:    return "Chitonga"
        case .lozi:     return "Silozi"
        }
    }

    /// False until a native speaker has signed the translation off.
    var isReviewed: Bool {
        switch self {
        case .english:  return true
        case .nyanja:   return false
        case .bemba:    return false
        case .tonga:    return false
        case .lozi:     return false
        }
    }

    var isAvailable: Bool {
        switch self {
        case .english:  return true
        case .nyanja:   return true
        case .bemba:    return true
        case .tonga:    return false
        case .lozi:     return false
        }
    }

    /// BCP-47 tag for on-device speech recognition, or nil where none exists.
    /// Nil is the honest answer for every Zambian language today.
    var speechLocale: String? {
        switch self {
        case .english:  return "en-ZA"
        case .nyanja:   return nil
        case .bemba:    return nil
        case .tonga:    return nil
        case .lozi:     return nil
        }
    }

    static var offered: [AppLanguage] { allCases.filter(\.isAvailable) }
}

enum Strings {
    static let table: [String: [String: String]] = [
        "en": {"app.tagline":"Find work. Get paid.","nav.findWork":"Find work","nav.tasks":"Tasks","nav.numbers":"Numbers","nav.chats":"Chats","nav.wallet":"Wallet","nav.office":"Office","nav.profile":"Profile","nav.hire":"Hire","nav.myJobs":"My jobs","nav.circle":"Chilimba","title.workNearYou":"Work near you","title.wallet":"Wallet","title.myNumbers":"My numbers","title.quickTasks":"Quick Tasks","title.hireSomeone":"Hire someone","title.jobsIPosted":"Jobs I posted","title.chilimba":"My Chilimba","money.balance":"Available balance","money.cashOut":"Cash out","money.getPaidEarly":"Get paid early","money.inEscrow":"Held safely","money.youReceive":"You receive","money.fee":"Our fee","money.cashNearMe":"Find cash near me","action.apply":"Apply","action.applied":"Application sent","action.message":"Message","action.send":"Send","action.back":"Back","action.search":"Search","action.postJob":"Post job","action.record":"Record a voice note","action.stop":"Stop","action.play":"Play","action.readAloud":"Read this aloud","word.yes":"Yes","word.no":"No","word.thanks":"Thank you","word.welcome":"Welcome","word.today":"Today","word.language":"Language","word.name":"Name","word.town":"Town","word.near":"Near you","word.urgent":"Urgent","circle.title":"Chilimba","circle.yourTurn":"Your turn","circle.members":"Members","circle.round":"Round","circle.contribute":"Contribute","circle.paidIn":"Paid in","circle.received":"Received","circle.waiting":"Still to contribute","voice.notReviewed":"This translation has not yet been checked by a native speaker. Anything that looks wrong probably is — please tell us.","voice.noSpeech":"Your phone cannot listen in this language yet, so type or send a voice note instead."},
        "ny": {"app.tagline":"Pezani ntchito. Landirani ndalama.","nav.findWork":"Pezani ntchito","nav.tasks":"Ntchito zazing'ono","nav.numbers":"Manambala","nav.chats":"Mauthenga","nav.wallet":"Chikwama","nav.office":"Ofesi","nav.profile":"Za ine","nav.hire":"Lembani munthu","nav.myJobs":"Ntchito zanga","nav.circle":"Chilimba","title.workNearYou":"Ntchito pafupi nanu","title.wallet":"Chikwama changa","title.myNumbers":"Manambala anga","title.quickTasks":"Ntchito zofulumira","title.hireSomeone":"Lembani wogwira ntchito","title.jobsIPosted":"Ntchito zomwe ndalemba","title.chilimba":"Chilimba changa","money.balance":"Ndalama zomwe muli nazo","money.cashOut":"Tulutsani ndalama","money.getPaidEarly":"Landirani ndalama msanga","money.inEscrow":"Zasungidwa bwino","money.youReceive":"Mudzalandira","money.fee":"Malipiro athu","money.cashNearMe":"Pezani ndalama pafupi","action.apply":"Funsani ntchito","action.applied":"Pempho latumizidwa","action.message":"Tumizani uthenga","action.send":"Tumizani","action.back":"Bwererani","action.search":"Sakani","action.postJob":"Lembani ntchito","action.record":"Nenani ndi mawu anu","action.stop":"Imani","action.play":"Mvetserani","action.readAloud":"Werengani mokweza","word.yes":"Inde","word.no":"Ayi","word.thanks":"Zikomo","word.welcome":"Takulandirani","word.today":"Lero","word.language":"Chinenero","word.name":"Dzina","word.town":"Tauni","word.near":"Pafupi nanu","word.urgent":"Mwachangu","circle.title":"Chilimba","circle.yourTurn":"Nthawi yanu","circle.members":"Mamembala","circle.round":"Kuzungulira","circle.contribute":"Perekani","circle.paidIn":"Zomwe mwapereka","circle.received":"Zomwe mwalandira","circle.waiting":"Sanaperekebe","voice.notReviewed":"Kumasulira uku sikunawunikidwe ndi mwiniwake wa chinenerochi. Ngati chinachake sichili bwino, tidziwitseni.","voice.noSpeech":"Foni yanu sikhoza kumvetsera chinenero ichi. Lembani kapena tumizani mawu anu."},
        "bem": {"app.tagline":"Fwayeni incito. Poleni indalama.","nav.findWork":"Fwayeni incito","nav.tasks":"Incito inono","nav.numbers":"Inambala","nav.chats":"Amashiwi","nav.wallet":"Icikwama","nav.office":"Ofeshi","nav.profile":"Pali ine","nav.hire":"Lembeni umuntu","nav.myJobs":"Incito shandi","nav.circle":"Icilimba","title.workNearYou":"Incito mupepi nenu","title.wallet":"Icikwama candi","title.myNumbers":"Inambala shandi","title.quickTasks":"Incito sha bwangu","title.hireSomeone":"Lembeni uwabomba","title.jobsIPosted":"Incito nalemba","title.chilimba":"Icilimba candi","money.balance":"Indalama mwakwata","money.cashOut":"Fumyeni indalama","money.getPaidEarly":"Poleni indalama bwangu","money.inEscrow":"Shasungwa bwino","money.youReceive":"Mukapokelela","money.fee":"Indalama shesu","money.cashNearMe":"Fwayeni indalama mupepi","action.apply":"Lombeni incito","action.applied":"Icilomba nacitumwa","action.message":"Tumeni ishiwi","action.send":"Tumeni","action.back":"Bwelelenimo","action.search":"Fwayeni","action.postJob":"Lembeni incito","action.record":"Landeni no kwasa kwenu","action.stop":"Imeni","action.play":"Umfweni","action.readAloud":"Belengeni mu kwasa","word.yes":"Ee","word.no":"Awe","word.thanks":"Natotela","word.welcome":"Mwaiseni","word.today":"Lelo","word.language":"Ululimi","word.name":"Ishina","word.town":"Itauni","word.near":"Mupepi nenu","word.urgent":"Bwangu bwangu","circle.title":"Icilimba","circle.yourTurn":"Inshita yenu","circle.members":"Abamembala","circle.round":"Ukushinguluka","circle.contribute":"Peeleni","circle.paidIn":"Ifyo mwapeela","circle.received":"Ifyo mwapokelela","circle.waiting":"Tabalapeela","voice.notReviewed":"Uku ukupilibula tabalakubebeta kuli abene ba lulimi. Nga cimo tacili bwino, tubebeni.","voice.noSpeech":"Ifoni yenu tailomfwa ulu lulimi. Lembeni nangula tumeni akwasa kenu."},
        "toi": {"app.tagline":"Jana mulimo. Tambula mali.","nav.findWork":"Jana mulimo","nav.tasks":"Tasks","nav.numbers":"Numbers","nav.chats":"Chats","nav.wallet":"Wallet","nav.office":"Office","nav.profile":"Profile","nav.hire":"Hire","nav.myJobs":"My jobs","nav.circle":"Chilimba","title.workNearYou":"Mulimo afwiifwi","title.wallet":"Wallet","title.myNumbers":"My numbers","title.quickTasks":"Quick Tasks","title.hireSomeone":"Hire someone","title.jobsIPosted":"Jobs I posted","title.chilimba":"My Chilimba","money.balance":"Mali ngomujisi","money.cashOut":"Gwisya mali","money.getPaidEarly":"Get paid early","money.inEscrow":"Held safely","money.youReceive":"You receive","money.fee":"Our fee","money.cashNearMe":"Find cash near me","action.apply":"Kumbila mulimo","action.applied":"Application sent","action.message":"Message","action.send":"Tuma","action.back":"Joka","action.search":"Yandaula","action.postJob":"Post job","action.record":"Record a voice note","action.stop":"Stop","action.play":"Play","action.readAloud":"Read this aloud","word.yes":"Inzya","word.no":"Pe","word.thanks":"Twalumba","word.welcome":"Mwabonwa","word.today":"Sunu","word.language":"Mwaambo","word.name":"Zina","word.town":"Town","word.near":"Afwiifwi","word.urgent":"Urgent","circle.title":"Chilimba","circle.yourTurn":"Your turn","circle.members":"Members","circle.round":"Round","circle.contribute":"Contribute","circle.paidIn":"Paid in","circle.received":"Received","circle.waiting":"Still to contribute","voice.notReviewed":"This translation has not yet been checked by a native speaker. Anything that looks wrong probably is — please tell us.","voice.noSpeech":"Your phone cannot listen in this language yet, so type or send a voice note instead."},
        "loz": {"app.tagline":"Fumana musebezi. Amuhela mali.","nav.findWork":"Fumana musebezi","nav.tasks":"Tasks","nav.numbers":"Numbers","nav.chats":"Chats","nav.wallet":"Wallet","nav.office":"Office","nav.profile":"Profile","nav.hire":"Hire","nav.myJobs":"My jobs","nav.circle":"Chilimba","title.workNearYou":"Musebezi bukaufi","title.wallet":"Wallet","title.myNumbers":"My numbers","title.quickTasks":"Quick Tasks","title.hireSomeone":"Hire someone","title.jobsIPosted":"Jobs I posted","title.chilimba":"My Chilimba","money.balance":"Mali eo munani ona","money.cashOut":"Zwisa mali","money.getPaidEarly":"Get paid early","money.inEscrow":"Held safely","money.youReceive":"You receive","money.fee":"Our fee","money.cashNearMe":"Find cash near me","action.apply":"Kupa musebezi","action.applied":"Application sent","action.message":"Message","action.send":"Luma","action.back":"Kuta","action.search":"Bata","action.postJob":"Post job","action.record":"Record a voice note","action.stop":"Stop","action.play":"Play","action.readAloud":"Read this aloud","word.yes":"Eni","word.no":"Awa","word.thanks":"Nitumezi","word.welcome":"Mu amuhelwe","word.today":"Kacenu","word.language":"Puo","word.name":"Libizo","word.town":"Town","word.near":"Bukaufi","word.urgent":"Urgent","circle.title":"Chilimba","circle.yourTurn":"Your turn","circle.members":"Members","circle.round":"Round","circle.contribute":"Contribute","circle.paidIn":"Paid in","circle.received":"Received","circle.waiting":"Still to contribute","voice.notReviewed":"This translation has not yet been checked by a native speaker. Anything that looks wrong probably is — please tell us.","voice.noSpeech":"Your phone cannot listen in this language yet, so type or send a voice note instead."},
    ]

    static let categoryNames: [String: [String: String]] = [
        "en": {},
        "ny": {"bricklaying":"Kumanga ndi njerwa","carpentry":"Ukalipentala","painting":"Kupenta","cleaning":"Kuyeretsa","laundry":"Kuchapa ndi kusita","childcare":"Kusunga ana","security":"Kulondera","farm":"Ulimi ndi munda","chef":"Kuphika","catering":"Kuphikira anthu","delivery":"Kutumiza katundu","loading":"Kusenza katundu","driving":"Kuyendetsa galimoto","tailoring":"Kusoka zovala","salon":"Kuluka tsitsi","barbering":"Kumeta","tutoring":"Kuphunzitsa","teaching":"Uphunzitsi","ministry":"Kulalikira","counselling":"Kulangiza","music":"Nyimbo","photography":"Kujambula","messenger":"Kunyamula mauthenga","home_services":"Ntchito zapakhomo"},
        "bem": {"bricklaying":"Ukukuula","carpentry":"Ubukalipentala","painting":"Ukupenta","cleaning":"Ukusangulula","laundry":"Ukucapa","childcare":"Ukusunga abana","security":"Ukulinda","farm":"Ubulimi","chef":"Ukwipika","catering":"Ukwipikila abantu","delivery":"Ukutwala ifintu","loading":"Ukusenda ifintu","driving":"Ukwendesha imotoka","tailoring":"Ukushona ifyakufwala","salon":"Ukuluka umushishi","barbering":"Ukubeya","tutoring":"Ukusambilisha","teaching":"Ubukafundisha","ministry":"Ukushimikila","counselling":"Ukufunda","music":"Inyimbo","photography":"Ukukopa","messenger":"Ukutwala amashiwi","home_services":"Incito sha pang'anda"},
        "toi": {"farm":"Bulimi"},
        "loz": {"farm":"Bulimi"},
    ]

    /// Falls back to English, then to the key — a missing string never blanks a screen.
    static func t(_ key: String, _ language: AppLanguage) -> String {
        table[language.rawValue]?[key] ?? table["en"]?[key] ?? key
    }

    static func categoryName(_ category: GigCategory, _ language: AppLanguage) -> String {
        categoryNames[language.rawValue]?[category.wireValue] ?? category.rawValue
    }
}
