// Generated by nchito-shared/generate.mjs from taxonomy.json — do not edit.
// Run `node nchito-shared/generate.mjs` after changing it.

import Foundation

/// The eight families a service belongs to. Groups exist because 39 flat
/// categories is a wall of chips on a phone and six screens on USSD; nobody
/// browses that. Every surface shows groups first.
enum ServiceGroup: String, CaseIterable, Identifiable, Codable {
    case trades     = "trades"
    case home       = "home"
    case food       = "food"
    case logistics  = "logistics"
    case style      = "style"
    case creative   = "creative"
    case learning   = "learning"
    case office     = "office"

    var id: String { rawValue }

    var label: String {
        switch self {
        case .trades:     return "Building & Trades"
        case .home:       return "Home & Care"
        case .food:       return "Food & Hospitality"
        case .logistics:  return "Transport & Errands"
        case .style:      return "Style & Lifestyle"
        case .creative:   return "Creative & Media"
        case .learning:   return "Learning & Guidance"
        case .office:     return "Office & Admin"
        }
    }

    /// One line on why these belong together, shown under the group heading.
    var blurb: String {
        switch self {
        case .trades:     return "The people who build and fix the physical thing."
        case .home:       return "Work inside someone's home, and the people in it."
        case .food:       return "Cooking, serving and feeding a room."
        case .logistics:  return "Moving things and people across town."
        case .style:      return "Hair, clothes, skin and looking after yourself."
        case .creative:   return "Design, sound, pictures and the web."
        case .learning:   return "Teaching, coaching and counsel."
        case .office:     return "The paperwork behind a small business."
        }
    }

    var emoji: String {
        switch self {
        case .trades:     return "🧱"
        case .home:       return "🏡"
        case .food:       return "🍲"
        case .logistics:  return "🛵"
        case .style:      return "✂️"
        case .creative:   return "🎨"
        case .learning:   return "📚"
        case .office:     return "🗂️"
        }
    }

    /// The label used where a whole menu has to fit one USSD screen.
    var shortLabel: String {
        switch self {
        case .trades:     return "Building"
        case .home:       return "Home & care"
        case .food:       return "Food & events"
        case .logistics:  return "Transport"
        case .style:      return "Hair & style"
        case .creative:   return "Design/media"
        case .learning:   return "Teaching"
        case .office:     return "Office work"
        }
    }

    var categories: [GigCategory] { GigCategory.allCases.filter { $0.group == self } }
}

/// A service someone can be hired for.
///
/// The rawValue is DISPLAY text and may be reworded freely. The value Postgres
/// stores is `wireValue`, which must never change once shipped: gig rows
/// written months ago still carry it.
enum GigCategory: String, Codable, CaseIterable, Identifiable {
    case bricklaying   = "Bricklaying & Masonry"
    case carpentry     = "Carpentry & Joinery"
    case painting      = "Painting & Decorating"
    case welding       = "Welding & Metalwork"
    case plumbing      = "Plumbing"
    case electrical    = "Electrical Services"
    case repairs       = "Repairs & Technical"
    case homeServices  = "Home Services"
    case cleaning      = "Cleaning"
    case laundry       = "Washing & Ironing"
    case security      = "Security & Guarding"
    case childcare     = "Childcare & Nannies"
    case farm          = "Farm & Garden"
    case catering      = "Catering"
    case chef          = "Chefs & Cooks"
    case restaurant    = "Restaurant & Bar Work"
    case events        = "Events & Functions"
    case delivery      = "Delivery & Errands"
    case messenger     = "Messengers"
    case loading       = "Loading & Moving"
    case driving       = "Driving"
    case beauty        = "Beauty & Grooming"
    case barbering     = "Barbershops"
    case salon         = "Salon & Hair"
    case cosmetics     = "Cosmetics & Make-up"
    case tailoring     = "Sewing & Tailoring"
    case lifestyle     = "Lifestyle & Wellness"
    case digital       = "Digital & Design"
    case webDesign     = "Web Design & Dev"
    case music         = "Music & Sound"
    case photography   = "Photo & Video"
    case tutoring      = "Tutoring & Lessons"
    case teaching      = "Teaching Services"
    case coaching      = "Coaching & Training"
    case counselling   = "Counselling"
    case ministry      = "Preaching & Ministry"
    case officeAdmin   = "Office & Admin Support"
    case bookkeeping   = "Bookkeeping & Accounts"
    case translation   = "Translation & Typing"

    var id: String { rawValue }

    /// Exactly the value the Postgres `gig_category` enum stores.
    var wireValue: String {
        switch self {
    case .bricklaying:   return "bricklaying"
    case .carpentry:     return "carpentry"
    case .painting:      return "painting"
    case .welding:       return "welding"
    case .plumbing:      return "plumbing"
    case .electrical:    return "electrical"
    case .repairs:       return "repairs"
    case .homeServices:  return "home_services"
    case .cleaning:      return "cleaning"
    case .laundry:       return "laundry"
    case .security:      return "security"
    case .childcare:     return "childcare"
    case .farm:          return "farm"
    case .catering:      return "catering"
    case .chef:          return "chef"
    case .restaurant:    return "restaurant"
    case .events:        return "events"
    case .delivery:      return "delivery"
    case .messenger:     return "messenger"
    case .loading:       return "loading"
    case .driving:       return "driving"
    case .beauty:        return "beauty"
    case .barbering:     return "barbering"
    case .salon:         return "salon"
    case .cosmetics:     return "cosmetics"
    case .tailoring:     return "tailoring"
    case .lifestyle:     return "lifestyle"
    case .digital:       return "digital"
    case .webDesign:     return "web_design"
    case .music:         return "music"
    case .photography:   return "photography"
    case .tutoring:      return "tutoring"
    case .teaching:      return "teaching"
    case .coaching:      return "coaching"
    case .counselling:   return "counselling"
    case .ministry:      return "ministry"
    case .officeAdmin:   return "office_admin"
    case .bookkeeping:   return "bookkeeping"
    case .translation:   return "translation"
        }
    }

    var group: ServiceGroup {
        switch self {
    case .bricklaying:   return .trades
    case .carpentry:     return .trades
    case .painting:      return .trades
    case .welding:       return .trades
    case .plumbing:      return .trades
    case .electrical:    return .trades
    case .repairs:       return .trades
    case .homeServices:  return .home
    case .cleaning:      return .home
    case .laundry:       return .home
    case .security:      return .home
    case .childcare:     return .home
    case .farm:          return .home
    case .catering:      return .food
    case .chef:          return .food
    case .restaurant:    return .food
    case .events:        return .food
    case .delivery:      return .logistics
    case .messenger:     return .logistics
    case .loading:       return .logistics
    case .driving:       return .logistics
    case .beauty:        return .style
    case .barbering:     return .style
    case .salon:         return .style
    case .cosmetics:     return .style
    case .tailoring:     return .style
    case .lifestyle:     return .style
    case .digital:       return .creative
    case .webDesign:     return .creative
    case .music:         return .creative
    case .photography:   return .creative
    case .tutoring:      return .learning
    case .teaching:      return .learning
    case .coaching:      return .learning
    case .counselling:   return .learning
    case .ministry:      return .learning
    case .officeAdmin:   return .office
    case .bookkeeping:   return .office
    case .translation:   return .office
        }
    }

    /// SF Symbol name.
    var icon: String {
        switch self {
    case .bricklaying:   return "building.2.fill"
    case .carpentry:     return "hammer.fill"
    case .painting:      return "paintbrush.fill"
    case .welding:       return "flame.fill"
    case .plumbing:      return "drop.fill"
    case .electrical:    return "bolt.fill"
    case .repairs:       return "wrench.and.screwdriver.fill"
    case .homeServices:  return "house.fill"
    case .cleaning:      return "sparkles"
    case .laundry:       return "washer.fill"
    case .security:      return "shield.lefthalf.filled"
    case .childcare:     return "figure.and.child.holdinghands"
    case .farm:          return "leaf.fill"
    case .catering:      return "fork.knife"
    case .chef:          return "frying.pan.fill"
    case .restaurant:    return "takeoutbag.and.cup.and.straw.fill"
    case .events:        return "party.popper.fill"
    case .delivery:      return "bicycle"
    case .messenger:     return "envelope.fill"
    case .loading:       return "shippingbox.fill"
    case .driving:       return "car.fill"
    case .beauty:        return "scissors"
    case .barbering:     return "comb.fill"
    case .salon:         return "hands.sparkles.fill"
    case .cosmetics:     return "paintpalette.fill"
    case .tailoring:     return "tshirt.fill"
    case .lifestyle:     return "figure.mind.and.body"
    case .digital:       return "laptopcomputer"
    case .webDesign:     return "globe"
    case .music:         return "music.note"
    case .photography:   return "camera.fill"
    case .tutoring:      return "book.fill"
    case .teaching:      return "graduationcap.fill"
    case .coaching:      return "figure.run"
    case .counselling:   return "heart.text.square.fill"
    case .ministry:      return "book.closed.fill"
    case .officeAdmin:   return "tray.full.fill"
    case .bookkeeping:   return "doc.text.fill"
    case .translation:   return "character.bubble.fill"
        }
    }

    /// The short form used where space is scarce — USSD screens, dense chips.
    var shortLabel: String {
        switch self {
    case .bricklaying:   return "Bricklaying"
    case .carpentry:     return "Carpentry"
    case .painting:      return "Painting"
    case .welding:       return "Welding"
    case .plumbing:      return "Plumbing"
    case .electrical:    return "Electrical"
    case .repairs:       return "Repairs"
    case .homeServices:  return "Home help"
    case .cleaning:      return "Cleaning"
    case .laundry:       return "Washing"
    case .security:      return "Security"
    case .childcare:     return "Childcare"
    case .farm:          return "Farm/garden"
    case .catering:      return "Catering"
    case .chef:          return "Chef/cook"
    case .restaurant:    return "Restaurant"
    case .events:        return "Events"
    case .delivery:      return "Delivery"
    case .messenger:     return "Messenger"
    case .loading:       return "Loading"
    case .driving:       return "Driving"
    case .beauty:        return "Beauty"
    case .barbering:     return "Barbering"
    case .salon:         return "Salon"
    case .cosmetics:     return "Cosmetics"
    case .tailoring:     return "Sewing"
    case .lifestyle:     return "Lifestyle"
    case .digital:       return "Design"
    case .webDesign:     return "Web design"
    case .music:         return "Music"
    case .photography:   return "Photo/video"
    case .tutoring:      return "Tutoring"
    case .teaching:      return "Teaching"
    case .coaching:      return "Coaching"
    case .counselling:   return "Counselling"
    case .ministry:      return "Ministry"
    case .officeAdmin:   return "Office admin"
    case .bookkeeping:   return "Bookkeeping"
    case .translation:   return "Translation"
        }
    }

    // from(wire:) comes from the WireRepresentable conformance declared in
    // WireFormat.swift, alongside every other enum that crosses the wire.
}
