// Generated by nchito-shared/generate.mjs from taxonomy.json — do not edit.
// Run `node nchito-shared/generate.mjs` after changing it.

export interface CategoryEntry {
  code: string;
  label: string;
  short: string;
  group: string;
}

export interface GroupEntry {
  code: string;
  label: string;
  /** The label used where a whole menu has to fit one USSD screen. */
  short: string;
}

export const SERVICE_GROUPS: GroupEntry[] = [
  { code: "trades", label: "Building & Trades", short: "Building" },
  { code: "home", label: "Home & Care", short: "Home & care" },
  { code: "food", label: "Food & Hospitality", short: "Food & events" },
  { code: "logistics", label: "Transport & Errands", short: "Transport" },
  { code: "style", label: "Style & Lifestyle", short: "Hair & style" },
  { code: "creative", label: "Creative & Media", short: "Design/media" },
  { code: "learning", label: "Learning & Guidance", short: "Teaching" },
  { code: "office", label: "Office & Admin", short: "Office work" },
];

export const CATEGORIES: CategoryEntry[] = [
  { code: "bricklaying", label: "Bricklaying & Masonry", short: "Bricklaying", group: "trades" },
  { code: "carpentry", label: "Carpentry & Joinery", short: "Carpentry", group: "trades" },
  { code: "painting", label: "Painting & Decorating", short: "Painting", group: "trades" },
  { code: "welding", label: "Welding & Metalwork", short: "Welding", group: "trades" },
  { code: "plumbing", label: "Plumbing", short: "Plumbing", group: "trades" },
  { code: "electrical", label: "Electrical Services", short: "Electrical", group: "trades" },
  { code: "repairs", label: "Repairs & Technical", short: "Repairs", group: "trades" },
  { code: "home_services", label: "Home Services", short: "Home help", group: "home" },
  { code: "cleaning", label: "Cleaning", short: "Cleaning", group: "home" },
  { code: "laundry", label: "Washing & Ironing", short: "Washing", group: "home" },
  { code: "security", label: "Security & Guarding", short: "Security", group: "home" },
  { code: "childcare", label: "Childcare & Nannies", short: "Childcare", group: "home" },
  { code: "farm", label: "Farm & Garden", short: "Farm/garden", group: "home" },
  { code: "catering", label: "Catering", short: "Catering", group: "food" },
  { code: "chef", label: "Chefs & Cooks", short: "Chef/cook", group: "food" },
  { code: "restaurant", label: "Restaurant & Bar Work", short: "Restaurant", group: "food" },
  { code: "events", label: "Events & Functions", short: "Events", group: "food" },
  { code: "delivery", label: "Delivery & Errands", short: "Delivery", group: "logistics" },
  { code: "messenger", label: "Messengers", short: "Messenger", group: "logistics" },
  { code: "loading", label: "Loading & Moving", short: "Loading", group: "logistics" },
  { code: "driving", label: "Driving", short: "Driving", group: "logistics" },
  { code: "beauty", label: "Beauty & Grooming", short: "Beauty", group: "style" },
  { code: "barbering", label: "Barbershops", short: "Barbering", group: "style" },
  { code: "salon", label: "Salon & Hair", short: "Salon", group: "style" },
  { code: "cosmetics", label: "Cosmetics & Make-up", short: "Cosmetics", group: "style" },
  { code: "tailoring", label: "Sewing & Tailoring", short: "Sewing", group: "style" },
  { code: "lifestyle", label: "Lifestyle & Wellness", short: "Lifestyle", group: "style" },
  { code: "digital", label: "Digital & Design", short: "Design", group: "creative" },
  { code: "web_design", label: "Web Design & Dev", short: "Web design", group: "creative" },
  { code: "music", label: "Music & Sound", short: "Music", group: "creative" },
  { code: "photography", label: "Photo & Video", short: "Photo/video", group: "creative" },
  { code: "tutoring", label: "Tutoring & Lessons", short: "Tutoring", group: "learning" },
  { code: "teaching", label: "Teaching Services", short: "Teaching", group: "learning" },
  { code: "coaching", label: "Coaching & Training", short: "Coaching", group: "learning" },
  { code: "counselling", label: "Counselling", short: "Counselling", group: "learning" },
  { code: "ministry", label: "Preaching & Ministry", short: "Ministry", group: "learning" },
  { code: "office_admin", label: "Office & Admin Support", short: "Office admin", group: "office" },
  { code: "bookkeeping", label: "Bookkeeping & Accounts", short: "Bookkeeping", group: "office" },
  { code: "translation", label: "Translation & Typing", short: "Translation", group: "office" },
];

export const categoriesIn = (group: string): CategoryEntry[] =>
  CATEGORIES.filter((c) => c.group === group);

export const categoryByCode = (code: string): CategoryEntry | undefined =>
  CATEGORIES.find((c) => c.code === code);
